<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pilih Metode Pembayaran_css-qnu5bt</name>
   <tag></tag>
   <elementGuidId>e5fbff8e-5819-41b4-9b8d-2b4681dcfb87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-qnu5bt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div/div/div/div[8]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84bb159e-be75-4412-beb0-615e8f5fdc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-qnu5bt</value>
      <webElementGuid>06c7d522-65e1-4262-89c2-e8a3c118e870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;css-1vt84pj&quot;]/div[@class=&quot;css-1wdgtgk&quot;]/div[@class=&quot;css-1s1t8no&quot;]/div[@class=&quot;css-1tc80em&quot;]/div[@class=&quot;css-1bn9zv9&quot;]/div[@class=&quot;css-qnu5bt&quot;]</value>
      <webElementGuid>f629ab2a-78af-4f5a-95fd-907a87320b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div/div[8]/div[2]/div/div/div/div</value>
      <webElementGuid>6340b9a4-1aa6-418c-ae74-37894bc0243c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div/div</value>
      <webElementGuid>ef38cb36-88e8-47fd-ba26-b6c38881b9ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
