<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kelas Saya</name>
   <tag></tag>
   <elementGuidId>66ebaa29-264c-439c-9d6e-48f5acf78c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-brk5lx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div[6]/div/div/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b10ff31e-5c2c-4caf-a1c2-7b90c52b53d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-brk5lx</value>
      <webElementGuid>ac0174e9-80c6-4b7f-a4ad-9a45451e120d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header-my-class-text</value>
      <webElementGuid>19691c6e-0c86-469b-8a77-d2232b99c7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas Saya</value>
      <webElementGuid>8ea83f7f-72a5-44ba-8d62-0ec6a93c450d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1vlel8&quot;]/div[@class=&quot;css-ed1os&quot;]/div[@class=&quot;css-bu0fqy&quot;]/div[@class=&quot;css-4i55s3&quot;]/div[1]/div[@class=&quot;css-nsi8t0&quot;]/div[@class=&quot;css-19ohtkr&quot;]/div[@class=&quot;css-cennm4&quot;]/a[@class=&quot;css-rwj60y&quot;]/p[@class=&quot;css-brk5lx&quot;]</value>
      <webElementGuid>6e21d37d-baa4-4f89-b0e6-a578720c3d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[6]/div/div/a/p</value>
      <webElementGuid>f1ca7eab-1e29-4ef4-b0d3-220d2fcfdce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf halaman yang kamu cari tidak dapat ditemukan'])[1]/preceding::p[1]</value>
      <webElementGuid>6fe3848f-3879-4283-b31d-503478dfc68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelas Saya']/parent::*</value>
      <webElementGuid>3c7febbc-44ee-4653-832b-d97eeaa11671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/p</value>
      <webElementGuid>99459042-e913-4199-9a12-50be96d4305f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kelas Saya' or . = 'Kelas Saya')]</value>
      <webElementGuid>698a4cae-08d7-4237-a1fc-ed008b7caaad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
