<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lihat Detail Kelas</name>
   <tag></tag>
   <elementGuidId>7c3e85c6-1982-47b5-b991-d0f78f176641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[2]/div/div/a/div/div/div[3]/div[6]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>99e0573b-37e5-44a0-a306-255cba29776e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>bede07e5-4430-4331-88e9-1033bc52ed89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail Kelas</value>
      <webElementGuid>7fa68dd1-f807-47ca-9d5b-ef1bbadedda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[2]/div[@class=&quot;css-1k6pjn0&quot;]/div[@class=&quot;css-1ibwzdy&quot;]/a[@class=&quot;css-rwj60y&quot;]/div[@class=&quot;css-1de9asv&quot;]/div[@class=&quot;css-1u0gzfm&quot;]/div[@class=&quot;css-1vkhgsa&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1qyzu3c&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>ed186fba-b8f2-4481-b2fb-34f205fb047f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[2]/div/div/a/div/div/div[3]/div[6]/div/p</value>
      <webElementGuid>9b4228f6-dcb5-479d-9459-62a58ff4d0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(500+ rating)'])[1]/following::p[4]</value>
      <webElementGuid>61d67346-daca-4c01-88c8-43609b8b3161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='try out'])[1]/following::p[5]</value>
      <webElementGuid>a5e4aebe-5c08-4642-b1b4-bf9cf7d2656d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tryout SKB CPNS Guru Bahasa Inggris'])[1]/preceding::p[1]</value>
      <webElementGuid>0ef4ce16-1901-454d-982d-f31a70bd9700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pembuat Soal CPNS'])[3]/preceding::p[1]</value>
      <webElementGuid>7af7f15b-865a-4802-b330-84cd2c3af0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Detail Kelas']/parent::*</value>
      <webElementGuid>fc595fd0-371f-48b0-9bf2-b351ef276c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/p</value>
      <webElementGuid>433cd117-a0bd-41c8-8c64-60a0266295e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lihat Detail Kelas' or . = 'Lihat Detail Kelas')]</value>
      <webElementGuid>9ebe8df1-80b8-41fb-b7a5-91f1514b36f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
