<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_PEMBELIAN</name>
   <tag></tag>
   <elementGuidId>126434fb-1213-4fb4-b0d7-a91a2ff85806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1tc80em > p.css-cif80s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[3]/div/div/div/div/div/span/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4295493f-aecf-4507-8ef5-bafa5151b35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-cif80s</value>
      <webElementGuid>6622057b-0edf-401d-a9a1-efa5329f2120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>title-tab</value>
      <webElementGuid>f018864c-a010-44c6-9c10-8260e5ac2c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PEMBELIAN</value>
      <webElementGuid>bd02fb67-22eb-4238-b7a4-35fc081a748e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[@class=&quot;css-sh4bij&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-1naokgy&quot;]/div[@class=&quot;css-i1qldj&quot;]/div[1]/div[@class=&quot;css-10826fd&quot;]/span[1]/div[@class=&quot;css-1v3ribi&quot;]/div[@class=&quot;css-1vkhs1&quot;]/div[@class=&quot;css-1tc80em&quot;]/p[@class=&quot;css-cif80s&quot;]</value>
      <webElementGuid>496f7a7f-ccc5-4e34-9f5e-ee64023c6f96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[3]/div/div/div/div/div/span/div/div/div/p</value>
      <webElementGuid>745fe3f3-c6c3-4875-a93b-9f691b354d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Selengkapnya'])[1]/following::p[3]</value>
      <webElementGuid>971a307d-a9cb-4de3-94d1-56a2be5eab9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::p[4]</value>
      <webElementGuid>1a4f294b-22b5-481a-8f59-bd344c9e625a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/preceding::p[4]</value>
      <webElementGuid>5524b072-c7f6-40d9-bc3c-afda2faa8580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dalam Progres'])[1]/preceding::p[4]</value>
      <webElementGuid>6224de51-7d07-45f4-a676-ac5ff654d43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PEMBELIAN']/parent::*</value>
      <webElementGuid>8590d5a9-063b-4aa9-a2e4-d310ba4fff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/p</value>
      <webElementGuid>45c198cd-227b-49cc-903b-05c6ccf17ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'PEMBELIAN' or . = 'PEMBELIAN')]</value>
      <webElementGuid>7a20088b-4127-4bab-8472-2d227c6da7df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
