<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Beri Rating</name>
   <tag></tag>
   <elementGuidId>10dc386b-41f6-49f3-9704-381749b88cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-o98ceo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[2]/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>47334f69-998b-4f31-a56f-a1959a74b7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-o98ceo</value>
      <webElementGuid>49166444-d1ab-4e78-b7aa-82a49681755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beri Rating</value>
      <webElementGuid>d18535c7-20e1-4948-ba4b-1c1460aac929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[1]/div[2]/div[@class=&quot;css-1tc80em&quot;]/div[@class=&quot;css-dlyqf&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-rfrfaq&quot;]/p[@class=&quot;css-o98ceo&quot;]</value>
      <webElementGuid>49ce184d-63ba-4e36-b179-28cdd4ce420a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[2]/div/div/p</value>
      <webElementGuid>433e33e2-7dda-4e2e-9176-34bddaed1de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::p[4]</value>
      <webElementGuid>6c91c1af-299d-4332-9313-d489200646fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beri Rating']/parent::*</value>
      <webElementGuid>281bb7b0-22c2-4371-bf1d-c2cbc89269f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/p</value>
      <webElementGuid>3089c94a-e089-4959-9068-538cfa216de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Beri Rating' or . = 'Beri Rating')]</value>
      <webElementGuid>1be12097-7767-4a10-9c6e-af093115396f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
