<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pel</name>
   <tag></tag>
   <elementGuidId>fabfb7c9-6438-4b4b-978e-2c1241628608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.css-28qup5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fda4ffe9-705c-480a-850f-27c8c53b0edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-28qup5</value>
      <webElementGuid>02738863-e85b-4f8f-a39f-61d791fca63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Berikan komentar Kamu di sini</value>
      <webElementGuid>242e2be7-15f6-4216-9c1f-45efd62f30b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>68079eab-ab6f-489c-b7c9-d765a2271339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b37d991-a2b4-4fab-91bb-1aa8a013e848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>feedback-field</value>
      <webElementGuid>b7da2bba-0690-40c2-ac29-0e19b76df38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pel</value>
      <webElementGuid>ce37337f-86d1-4428-8c7d-5a2acf7feaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-1xs2txo&quot;]/div[@class=&quot;css-1x6t52p&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-13738c3&quot;]/div[@class=&quot;css-14ati96&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/textarea[@class=&quot;css-28qup5&quot;]</value>
      <webElementGuid>f1241aa3-41f7-4c8d-b0db-66f7d0adaa33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>81c4419e-74e5-4237-a2e0-b3c30fb89d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div[7]/form/div/textarea</value>
      <webElementGuid>f6c3303e-51e3-494e-8507-0401155a546f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::textarea[1]</value>
      <webElementGuid>5cbe5917-c9e0-43f8-a2ec-dec24220571a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum 10 karakter'])[1]/preceding::textarea[1]</value>
      <webElementGuid>607bb25c-86f1-40e5-95ad-3b7c4766b232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pel']/parent::*</value>
      <webElementGuid>55ae043d-937c-4776-8859-739daa76cd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b5e669e4-4f47-4a64-8fea-5d4125149398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Berikan komentar Kamu di sini' and @type = 'text' and (text() = 'pel' or . = 'pel')]</value>
      <webElementGuid>4feabe3f-a14f-49ad-9d7d-057ba541e912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
