<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pelati</name>
   <tag></tag>
   <elementGuidId>bea257cb-0b9c-4bfc-aa79-870bd73f8a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.css-28qup5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3ce2af0b-1b77-4365-8dc4-1a3be44e3d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-28qup5</value>
      <webElementGuid>e5bf9bb7-e78c-4b7c-aa6c-7f7568241ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Berikan komentar Kamu di sini</value>
      <webElementGuid>cf664bc7-2dcf-4922-befa-74e4f20f3f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3aa3c823-fbc4-4b19-8c30-80fd25399b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b49fbb79-7e8b-4953-900b-91adb65da072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>feedback-field</value>
      <webElementGuid>e442f58a-9e4e-4cf8-b086-c6a0ba647be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelati</value>
      <webElementGuid>0b813ecb-6ffb-4242-981f-fd21c71005b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-1xs2txo&quot;]/div[@class=&quot;css-1x6t52p&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-13738c3&quot;]/div[@class=&quot;css-14ati96&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/textarea[@class=&quot;css-28qup5&quot;]</value>
      <webElementGuid>a26a13c8-e31a-441d-87f4-2a7bb3b76f4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>03040c72-bb19-49af-b2a9-f4cb0ac8238e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div[7]/form/div/textarea</value>
      <webElementGuid>013e5502-250a-48ac-a52a-65e865afc815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::textarea[1]</value>
      <webElementGuid>5b7554f6-d3aa-46fc-9fc6-097559a9f72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum 10 karakter'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b5442a37-b7a8-494e-8acf-486a5728e2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pelati']/parent::*</value>
      <webElementGuid>47cbb82b-9b8c-40e3-8590-dccf3b7d7c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4f9b3e8d-f14c-4fc1-b888-2940b9b6da2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Berikan komentar Kamu di sini' and @type = 'text' and (text() = 'pelati' or . = 'pelati')]</value>
      <webElementGuid>9178b37b-678e-4464-9242-b484e679221f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
