<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pelatih</name>
   <tag></tag>
   <elementGuidId>3bab9655-dc11-4cb0-97a5-57d3ad2a121b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.css-28qup5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>661d68d5-90d9-4c0e-9c36-3d10bcaaccc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-28qup5</value>
      <webElementGuid>ec4d4e72-aeec-411c-b6f8-637853c5fc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Berikan komentar Kamu di sini</value>
      <webElementGuid>1fc63b62-fc72-4073-b0de-33d663509efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2f366103-6b51-4d2a-878f-39f3d861c7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>465b1e38-8136-4004-ab10-be09d7625859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>feedback-field</value>
      <webElementGuid>a73075a0-9af8-4128-8a59-41049e3278b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelatih</value>
      <webElementGuid>0324d6a3-6904-46a9-8a16-2966449a7e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-1xs2txo&quot;]/div[@class=&quot;css-1x6t52p&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-13738c3&quot;]/div[@class=&quot;css-14ati96&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/textarea[@class=&quot;css-28qup5&quot;]</value>
      <webElementGuid>19fb21c3-6f2b-4141-b6e3-c50cd5ed52cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>55224bfa-6eb0-4098-88c5-2b6df222b217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div[7]/form/div/textarea</value>
      <webElementGuid>c51dce2e-50cf-404c-9a99-588a0fe98fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::textarea[1]</value>
      <webElementGuid>fa740112-7bd7-43d1-babc-4abf36a3ac2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum 10 karakter'])[1]/preceding::textarea[1]</value>
      <webElementGuid>673d2ad4-1d69-42fd-b721-002bb08becd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pelatih']/parent::*</value>
      <webElementGuid>4fceb57a-9950-4f8b-a246-b98ed9f8017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fb36ad38-424e-4181-8f85-a96d07d6267c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Berikan komentar Kamu di sini' and @type = 'text' and (text() = 'pelatih' or . = 'pelatih')]</value>
      <webElementGuid>b9dc0eaa-5624-4da6-80a2-b3553fe6d9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
