<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pelatihan sa</name>
   <tag></tag>
   <elementGuidId>f8a444e8-11fd-4a84-849e-7e209738bdde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.css-uy4nil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>32896759-ac61-4845-88ec-b2450549c410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-uy4nil</value>
      <webElementGuid>629cb6d7-352a-48fd-b1f5-e08dc4e78402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Berikan komentar Kamu di sini</value>
      <webElementGuid>eb364f0a-1ce0-4774-8727-aae6772cded9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>60401e20-05e2-4f31-b8c0-891bf23d5933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aaead010-6ea1-41fb-804a-d41e523c7d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>feedback-field</value>
      <webElementGuid>b0120757-77a0-45c1-b9ad-1348b7891ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelatihan sa</value>
      <webElementGuid>c2ba90e7-215c-4509-a12d-035933727aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-1xs2txo&quot;]/div[@class=&quot;css-1x6t52p&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-13738c3&quot;]/div[@class=&quot;css-14ati96&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/textarea[@class=&quot;css-uy4nil&quot;]</value>
      <webElementGuid>6e1251df-a3e2-419c-9d53-e927af2bc309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>91ce82fc-ea0d-4ce6-9391-4cf79a324c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div[7]/form/div/textarea</value>
      <webElementGuid>d520422c-7196-4c25-8b42-16cfe18e0272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::textarea[1]</value>
      <webElementGuid>57749403-5bf3-42a6-bf91-db3e17c99423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukan tidak valid'])[1]/preceding::textarea[1]</value>
      <webElementGuid>33772ef4-a118-4761-a29f-91084e698a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pelatihan sa']/parent::*</value>
      <webElementGuid>69393c01-2873-4561-9138-c0ae2b8a3efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>822297c3-2229-41fd-9472-8de5a03d4a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Berikan komentar Kamu di sini' and @type = 'text' and (text() = 'pelatihan sa' or . = 'pelatihan sa')]</value>
      <webElementGuid>49b2639a-53c6-4ee6-992f-7d1ce7c11d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
