<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pelatihan sangat memba</name>
   <tag></tag>
   <elementGuidId>f83874c1-6eff-42c0-9af5-fc39ab1fd6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.css-uy4nil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d6ed6c3-36dc-4a92-9da6-71ea870f4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-uy4nil</value>
      <webElementGuid>25c15ce6-2985-4923-8682-ea5ad80cbcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Berikan komentar Kamu di sini</value>
      <webElementGuid>d5515d5e-56c2-4c20-a9e4-a6000d31c75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>826ff774-fb1f-4990-8942-b3282a41dbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>524f6a68-c748-4854-bda9-1bb509c669bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>feedback-field</value>
      <webElementGuid>00c85119-e0e9-4c04-8a11-1c20d47e0933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelatihan sangat memba</value>
      <webElementGuid>4f574be0-c705-49f7-adb7-06bb9db1ee64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-1xs2txo&quot;]/div[@class=&quot;css-1x6t52p&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-13738c3&quot;]/div[@class=&quot;css-14ati96&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/textarea[@class=&quot;css-uy4nil&quot;]</value>
      <webElementGuid>cdd502a7-0258-42cd-a32e-40a1de1149f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>6c9f2678-06e1-4c49-9983-e658ea7b218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div[7]/form/div/textarea</value>
      <webElementGuid>aac7a3d1-d6e7-4265-ba60-87e380624d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[1]/following::textarea[1]</value>
      <webElementGuid>3d8a41a7-3544-4b95-a110-2857b3110850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukan tidak valid'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2e2fd7e0-0560-4561-9df7-4dc7ca31e834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pelatihan sangat memba']/parent::*</value>
      <webElementGuid>43ab40f5-f5b2-4986-8b49-0a9acc631695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7bf4a448-0430-4069-b001-a5cd5a6b0033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Berikan komentar Kamu di sini' and @type = 'text' and (text() = 'pelatihan sangat memba' or . = 'pelatihan sangat memba')]</value>
      <webElementGuid>210cfe70-0405-4d3e-828f-628a87e821ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
