<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Exam</name>
   <tag></tag>
   <elementGuidId>69caaca6-b082-40d9-8de7-83dc36e0dfab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[11]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>805454c6-2ec7-4629-bc3b-16f6fb4c7916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1nl6p5k</value>
      <webElementGuid>9894691d-a674-4936-aa2a-955a3cf1d04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>active-test</value>
      <webElementGuid>a3b67a9e-756b-4b54-9b0d-2f7228dbc643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exam</value>
      <webElementGuid>f0332a58-4d6a-45dd-92d5-6747e1bbfc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[1]/div[@class=&quot;css-14006f7&quot;]/div[@class=&quot;css-qqsmud&quot;]/p[@class=&quot;css-1nl6p5k&quot;]</value>
      <webElementGuid>41324a3f-85d9-4605-b228-e05b70ae6866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[11]/p</value>
      <webElementGuid>0de200e2-a16c-4bbb-bfa1-541ab6276c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menggunakan Data Science untuk Mengembangkan Bisnis bagi Data Scientist'])[1]/following::p[148]</value>
      <webElementGuid>d3e2c510-6618-42e1-91ce-7318668483e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu telah menyelesaikan kelas ini dengan nilai yang memuaskan.'])[1]/preceding::p[4]</value>
      <webElementGuid>b5a47c49-1868-4c9b-8afa-54bfae10b65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu telah mendapatkan dua sertifikat sekaligus:'])[1]/preceding::p[5]</value>
      <webElementGuid>3989f441-df3d-4e26-a453-8d37b6f1d349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exam']/parent::*</value>
      <webElementGuid>bd391453-0871-4bbc-9c4d-44d7bd028c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/p</value>
      <webElementGuid>cde42e36-628b-497d-acf1-5b3c82550332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Exam' or . = 'Exam')]</value>
      <webElementGuid>b35e445a-1993-459a-8ec6-c389141dd670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
