<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>6a8e8c82-281c-49f7-a8d3-498aac7c1929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>72e76634-8f92-47c4-99ce-86504b5bc706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-z88rz8</value>
      <webElementGuid>d4f87908-6d98-400d-a312-a5cac5421e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>89c0c2bb-bd8c-4f4d-951c-4ad57f944d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[2]/div[@class=&quot;css-1a66z0j&quot;]/div[@class=&quot;css-nukipx&quot;]/div[@class=&quot;css-avf9nl&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-gclzmy&quot;]/div[@class=&quot;css-cennm4&quot;]/p[@class=&quot;css-z88rz8&quot;]</value>
      <webElementGuid>5d50380a-2132-42fe-8058-76980eca3cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/p</value>
      <webElementGuid>87432bf7-2b43-412d-b686-e9c41c4c3edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menggunakan Data Science untuk Mengembangkan Bisnis bagi Data Scientist'])[1]/following::p[156]</value>
      <webElementGuid>34e10c25-0ec3-4635-adb6-78186bf195dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>b2ebbd6f-0249-4257-b734-a39fadc20a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/p</value>
      <webElementGuid>f8e6d968-ade2-402c-8afa-adca769b8993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>2dc3e616-7afc-4c2c-be23-9e35efc3f1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
