<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DaftarMasuk</name>
   <tag></tag>
   <elementGuidId>5dd4e889-ac2a-4c46-a873-c7f8de84fcce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/span/div/span/div/div/div/div/div[2]/div/a/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30d23cb8-b8cf-447e-bf05-bb1fc9c8cb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>$body</value>
      <webElementGuid>fd12b038-312f-4d79-9fbe-fa87dc4514c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> is_SizableText font_var(--body) _ff-4xduee _col-1edgtlp _textDecorationLine-none _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1az8dqv _lh-1nheiq6 _fos-lbyol5 _ls-fna3d2</value>
      <webElementGuid>6a036550-ae62-4f7c-a839-3541b7981667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar/Masuk</value>
      <webElementGuid>03d70694-3031-437b-8308-d567d8ec49c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/span[@class=&quot;t_sub_theme t_light _dsp_contents&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/span[@class=&quot;t_sub_theme t_dark _dsp_contents&quot;]/div[@class=&quot;is_YStack  _bg-rsi03t _ox-hidden _oy-hidden _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_YStack  _dsp-_gtMd_flex _dsp-none _bg-57q3d6 _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_YStack  _w-_gtLg_12c3duh _w-_gtMd_11v1rga _w-_gtSm_11e0523 _pr-1aj148u _pl-1aj148u _w-10011 _mt-auto _mr-auto _mb-auto _ml-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _ai-center _jc-7aqssh _pr-1aj149p _pl-1aj149p _pt-1aj149p _pb-1aj149p _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_XStack  _ai-center _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_YStack  _dsp-_gtXs_flex _dsp-none _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/a[1]/button[@class=&quot;is_Button  _bg-0hover-1cjjmmp _bg-0active-1asf2wv _bg-0focus-1bl4kz9 _btw-0focus-1cahg3 _brw-0focus-1cahg3 _bbw-0focus-1cahg3 _blw-0focus-1cahg3 _btc-0focus-19yqz7f _brc-0focus-19yqz7f _bbc-0focus-19yqz7f _blc-0focus-19yqz7f _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _bg-1vw8u7g _h-1sn2xu1 _pr-l3f357 _pl-l3f357 _btlr-r555ll _btrr-r555ll _bbrr-r555ll _bblr-r555ll _btc-d0tu4cw03 _brc-d0tu4cw03 _bbc-d0tu4cw03 _blc-d0tu4cw03 _ai-center _jc-center _cur-pointer _fd-row _fw-nowrap _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/span[@class=&quot;is_SizableText font_var(--body) _ff-4xduee _col-1edgtlp _textDecorationLine-none _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1az8dqv _lh-1nheiq6 _fos-lbyol5 _ls-fna3d2&quot;]</value>
      <webElementGuid>086010fe-82e9-4a07-b73f-ee154ed0a921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/span/div/span/div/div/div/div/div[2]/div/a/button/span</value>
      <webElementGuid>a1b73293-15d0-4c0f-8d82-485783ca9518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::span[4]</value>
      <webElementGuid>93927317-5137-40e9-afcf-662ebda8e0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[2]/following::span[9]</value>
      <webElementGuid>cfd02640-8ffe-47a3-81de-45e89c3e904e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::span[2]</value>
      <webElementGuid>01b19d75-5d99-461b-b650-4090e2a04b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari digital marketing'])[1]/preceding::span[5]</value>
      <webElementGuid>a37ce670-5f04-4aec-98fb-c0e2792ed7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar/Masuk']/parent::*</value>
      <webElementGuid>78c42e18-6c83-479d-ac18-e219a52bdc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>256a10e5-7d46-4851-a996-453037381ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar/Masuk' or . = 'Daftar/Masuk')]</value>
      <webElementGuid>c65645cc-d9e0-4887-bac5-37319dfa928e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
