<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>c2885eed-aa61-443b-9ced-2294a854b841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':rt:']/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>09cda7d7-9462-40e8-a28a-eb73511f2328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>$body</value>
      <webElementGuid>dac2e758-01d4-4cc8-be28-0dfb4c0862cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> is_SizableText font_body _col-1ckdj6p _ff-4yewjq _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1cfkoc4 _lh-36px _fos-32px</value>
      <webElementGuid>92efad54-fcd8-4b06-b59a-dba3165396fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>b70b6a24-4c7c-47ed-9492-5ca51bdea93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:&quot;)/div[@class=&quot;css-175oi2r r-1loqt21 r-1otgn73&quot;]/span[@class=&quot;is_SizableText font_body _col-1ckdj6p _ff-4yewjq _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1cfkoc4 _lh-36px _fos-32px&quot;]</value>
      <webElementGuid>a10985bb-e0c4-4d24-8863-8b12f2621db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rt:']/div[2]/span</value>
      <webElementGuid>e7c3ef24-cfd4-454b-95ee-b3616c8c5380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[2]/following::span[3]</value>
      <webElementGuid>b43a0e4a-ae7a-4fc7-9f3f-3c6b65231b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas Saya'])[1]/following::span[5]</value>
      <webElementGuid>fbee360c-cc77-4dc2-8ff3-15542f3e0bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>bc1be16a-1fa9-4f3b-a889-c322d11876cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>88b22ca8-9c5d-419d-b457-3d07d58efac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '+' or . = '+')]</value>
      <webElementGuid>95581ef4-57e2-4955-b34f-7f03735a004c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
