<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>5299d1ac-0674-43c2-9436-030ca29167ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-q7mxjq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div[5]/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eab093c5-6489-43e0-97ee-eb36fe6f7b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q7mxjq</value>
      <webElementGuid>cb7b5b09-e954-46e5-a567-997d48abfb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>c03b3121-216b-4d4b-86e1-548e0d177823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-oprbr7&quot;]/div[@class=&quot;css-1o4axai&quot;]/div[@class=&quot;css-15wy7rm&quot;]/div[@class=&quot;css-19dy3j4&quot;]/p[@class=&quot;css-q7mxjq&quot;]</value>
      <webElementGuid>eef71490-d4f9-4206-a02f-27ff5c10a0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div[5]/div/div/div/div/p</value>
      <webElementGuid>b64d2e38-3cfd-4ce0-b9f7-e0d451482a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pembuat Soal CPNS'])[3]/following::p[6]</value>
      <webElementGuid>b02ac44d-beef-4b31-9a97-02c6326d5f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Out SKD CPNS Terlengkap'])[2]/following::p[6]</value>
      <webElementGuid>be0c8496-15f3-43cc-af81-09a13477d833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div/p</value>
      <webElementGuid>5c8e8522-e2f7-4558-b13e-3b68d99b25a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '+' or . = '+')]</value>
      <webElementGuid>0c5592ae-440f-42bd-b9fc-0ee3df8b7bba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
