<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_css-11aywtz r-6taxm2 is_Inpu_8332b3</name>
   <tag></tag>
   <elementGuidId>53a84ae3-d034-4831-aed0-d7ebdc5e5fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-11aywtz.r-6taxm2.is_Input.font_body._btc-0hover-1byp41v._brc-0hover-1byp41v._bbc-0hover-1byp41v._blc-0hover-1byp41v._btc-0focus-1b0a2ef._brc-0focus-1b0a2ef._bbc-0focus-1b0a2ef._blc-0focus-1b0a2ef._btw-0focus-2px._brw-0focus-2px._bbw-0focus-2px._blw-0focus-2px._mr-0focus--1px._ml-0focus--1px._bbs-0focus-solid._bts-0focus-solid._bls-0focus-solid._brs-0focus-solid._pr-lrpiu9._fg-1._fs-1._fb-auto._btlr-lmimb3._btrr-lmimb3._bbrr-lmimb3._bblr-lmimb3._pt-1aj149p._pb-1aj149p._pl-1aj149p._btc-1ckdigv._brc-1ckdigv._bbc-1ckdigv._blc-1ckdigv._bg-1ckdj6p._col-d0tu4wolg._ff-4xduee._h-qnlo9k._btw-1px._brw-1px._bbw-1px._blw-1px._outlineWidth-0px._miw-0px._bbs-solid._bts-solid._bls-solid._brs-solid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99b7cda1-a7bf-4fd3-b3a1-8dcac80b63f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kamu ingin menguasai skill apa hari ini?</value>
      <webElementGuid>96e12c72-7ffa-46b5-bdb6-4311feb32056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>fd87c50f-1e0b-43a3-aa79-eb772954d4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a56ed39b-a483-465f-813b-99376efe960f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0e9b46f1-3293-4946-91f0-81c939121f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fdaf5851-c262-4ed6-8c46-a81c460ab29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23504c44-5c3a-4d96-926d-02db090bb0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27075304-21dc-49b6-8812-0f1f1169d4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-6taxm2 is_Input font_body _btc-0hover-1byp41v _brc-0hover-1byp41v _bbc-0hover-1byp41v _blc-0hover-1byp41v _btc-0focus-1b0a2ef _brc-0focus-1b0a2ef _bbc-0focus-1b0a2ef _blc-0focus-1b0a2ef _btw-0focus-2px _brw-0focus-2px _bbw-0focus-2px _blw-0focus-2px _mr-0focus--1px _ml-0focus--1px _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _pr-lrpiu9 _fg-1 _fs-1 _fb-auto _btlr-lmimb3 _btrr-lmimb3 _bbrr-lmimb3 _bblr-lmimb3 _pt-1aj149p _pb-1aj149p _pl-1aj149p _btc-1ckdigv _brc-1ckdigv _bbc-1ckdigv _blc-1ckdigv _bg-1ckdj6p _col-d0tu4wolg _ff-4xduee _h-qnlo9k _btw-1px _brw-1px _bbw-1px _blw-1px _outlineWidth-0px _miw-0px _bbs-solid _bts-solid _bls-solid _brs-solid</value>
      <webElementGuid>22db883f-5047-4eae-8e6a-752d97277715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/span[@class=&quot;t_sub_theme t_light _dsp_contents&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/span[@class=&quot;t_sub_theme t_dark _dsp_contents&quot;]/div[@class=&quot;is_YStack  _bg-rsi03t _ox-hidden _oy-hidden _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_YStack  _dsp-_gtMd_flex _dsp-none _bg-57q3d6 _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_YStack  _w-_gtLg_12c3duh _w-_gtMd_11v1rga _w-_gtSm_11e0523 _pr-1aj148u _pl-1aj148u _w-10011 _mt-auto _mr-auto _mb-auto _ml-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _ai-center _jc-7aqssh _pr-1aj149p _pl-1aj149p _pt-1aj149p _pb-1aj149p _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_XStack  _dsp-_gtXs_flex _ai-center _fg-1 _fs-1 _fb-auto _dsp-none _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_XStack  _pos-relative _fd-row _miw-0px _mih-0px _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/input[@class=&quot;css-11aywtz r-6taxm2 is_Input font_body _btc-0hover-1byp41v _brc-0hover-1byp41v _bbc-0hover-1byp41v _blc-0hover-1byp41v _btc-0focus-1b0a2ef _brc-0focus-1b0a2ef _bbc-0focus-1b0a2ef _blc-0focus-1b0a2ef _btw-0focus-2px _brw-0focus-2px _bbw-0focus-2px _blw-0focus-2px _mr-0focus--1px _ml-0focus--1px _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _pr-lrpiu9 _fg-1 _fs-1 _fb-auto _btlr-lmimb3 _btrr-lmimb3 _bbrr-lmimb3 _bblr-lmimb3 _pt-1aj149p _pb-1aj149p _pl-1aj149p _btc-1ckdigv _brc-1ckdigv _bbc-1ckdigv _blc-1ckdigv _bg-1ckdj6p _col-d0tu4wolg _ff-4xduee _h-qnlo9k _btw-1px _brw-1px _bbw-1px _blw-1px _outlineWidth-0px _miw-0px _bbs-solid _bts-solid _bls-solid _brs-solid&quot;]</value>
      <webElementGuid>c8d18150-9e7f-43b9-898e-979f6608ab16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>f8c97fe9-8958-49dc-a374-01f8e316b5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/span/div/span/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3b7e08c3-d385-41a1-bf9f-e54789f7624b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7903ff3e-8101-4782-b169-37d50b43d1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kamu ingin menguasai skill apa hari ini?' and @type = 'text']</value>
      <webElementGuid>4be2c1c6-b403-4aec-b865-3b651901afa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
