<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DaftarMasuk</name>
   <tag></tag>
   <elementGuidId>641456ea-402b-4ade-91d0-0ec5202fd031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/span/div/span/div/div/div/div/div[2]/div/a/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7b40db5-b71a-41d9-aaa5-880763a5f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>$body</value>
      <webElementGuid>e240a8bd-3a59-47bc-9aad-ff88550ff885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> is_SizableText font_var(--body) _ff-4xduee _col-1edgtlp _textDecorationLine-none _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1az8dqv _lh-1nheiq6 _fos-lbyol5 _ls-fna3d2</value>
      <webElementGuid>54f55dcc-22f7-40e8-b038-10a63497d212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar/Masuk</value>
      <webElementGuid>713bf8d2-58a5-41be-8d4d-8a335216df06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/span[@class=&quot;t_sub_theme t_light _dsp_contents&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/span[@class=&quot;t_sub_theme t_dark _dsp_contents&quot;]/div[@class=&quot;is_YStack  _bg-rsi03t _ox-hidden _oy-hidden _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_YStack  _dsp-_gtMd_flex _dsp-none _bg-57q3d6 _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_YStack  _w-_gtLg_12c3duh _w-_gtMd_11v1rga _w-_gtSm_11e0523 _pr-1aj148u _pl-1aj148u _w-10011 _mt-auto _mr-auto _mb-auto _ml-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _ai-center _jc-7aqssh _pr-1aj149p _pl-1aj149p _pt-1aj149p _pb-1aj149p _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_XStack  _ai-center _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_YStack  _dsp-_gtXs_flex _dsp-none _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/a[1]/button[@class=&quot;is_Button  _bg-0hover-1cjjmmp _bg-0active-1asf2wv _bg-0focus-1bl4kz9 _btw-0focus-1cahg3 _brw-0focus-1cahg3 _bbw-0focus-1cahg3 _blw-0focus-1cahg3 _btc-0focus-19yqz7f _brc-0focus-19yqz7f _bbc-0focus-19yqz7f _blc-0focus-19yqz7f _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _bg-1vw8u7g _h-1sn2xu1 _pr-l3f357 _pl-l3f357 _btlr-r555ll _btrr-r555ll _bbrr-r555ll _bblr-r555ll _btc-d0tu4cw03 _brc-d0tu4cw03 _bbc-d0tu4cw03 _blc-d0tu4cw03 _ai-center _jc-center _cur-pointer _fd-row _fw-nowrap _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/span[@class=&quot;is_SizableText font_var(--body) _ff-4xduee _col-1edgtlp _textDecorationLine-none _mt-0px _mr-0px _mb-0px _ml-0px _ww-break-word _bxs-border-box _dsp-inline _fow-1az8dqv _lh-1nheiq6 _fos-lbyol5 _ls-fna3d2&quot;]</value>
      <webElementGuid>381e9aa5-5751-4698-99db-56063c599a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/span/div/span/div/div/div/div/div[2]/div/a/button/span</value>
      <webElementGuid>cb20678f-cfca-445e-a30b-d3a88f227e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::span[4]</value>
      <webElementGuid>d65a89ad-f397-4267-b315-d42da5b5619c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::span[9]</value>
      <webElementGuid>14d5b296-ca72-4844-acdd-7702f5ba4dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::span[2]</value>
      <webElementGuid>adf49600-ecb1-4724-9e88-679cf8d9b456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari digital marketing'])[1]/preceding::span[5]</value>
      <webElementGuid>df31752a-3e3d-449e-9956-a72b73d8c3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar/Masuk']/parent::*</value>
      <webElementGuid>b9b64792-6a57-44f0-bb2c-fd417a4319ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>3e08916a-52db-4bc5-8c92-b86467630104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar/Masuk' or . = 'Daftar/Masuk')]</value>
      <webElementGuid>cdf0ff65-6213-47a1-94c5-3301c67f39d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
