<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dengan akun Prakerja kamu_css-1j6p4yb</name>
   <tag></tag>
   <elementGuidId>d3411af4-ab6e-4fd1-b332-613145970cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f99c17d5-8133-4958-a897-58c15336422b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1j6p4yb</value>
      <webElementGuid>5b58dc69-40ce-4c14-a569-3f39b925c258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>2d8d822f-d462-4d5d-9a13-220bf89f5f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9619c73-e1e5-470a-92e7-a03ca91354a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>d6596b81-3663-4205-bb46-bdb41b9e1127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[@class=&quot;css-fq9n1m&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1rmhad2&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/input[@class=&quot;css-1j6p4yb&quot;]</value>
      <webElementGuid>dcf24d1a-9024-4b9b-88c5-6a04a0926462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>a6322fcd-ad11-45c3-9404-6602d4d0c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/form/div[3]/input</value>
      <webElementGuid>2140ec32-4583-4827-93a5-dd521cd265e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>06390e88-bc0f-4711-a548-f2c889b965b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @type = 'text']</value>
      <webElementGuid>77feee8c-7279-4e7c-9021-0aad00cdbe76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
