<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Daftar</name>
   <tag></tag>
   <elementGuidId>77444d99-4426-42a1-9f0c-5d1b5fbe0167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-zwgrk9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div/div/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9a5c4271-b0bd-4cec-83c3-ec25b7a0c56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-zwgrk9</value>
      <webElementGuid>8c83fdf2-9cd8-4e1d-8cd0-3c7bef1e1554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>title-tab</value>
      <webElementGuid>3ed746ab-ab1b-4b26-9f77-ad48ff1a8b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>edf8436a-ce8c-412c-b9e1-f785f7b69940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-1naokgy&quot;]/div[@class=&quot;css-3dmmu0&quot;]/div[@class=&quot;css-1v3ribi&quot;]/div[@class=&quot;css-qe9cpj&quot;]/div[@class=&quot;css-1tc80em&quot;]/p[@class=&quot;css-zwgrk9&quot;]</value>
      <webElementGuid>36effd9d-19f2-4e83-bf43-cbde9b154b78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div/div/div[2]/div/div/p</value>
      <webElementGuid>58d552f3-e178-4d2b-85b1-d5f11b3c534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perluas Wawasan, Perbanyak Kesempatan'])[1]/following::p[5]</value>
      <webElementGuid>32570240-99fa-4dd1-a164-c7adc2c2f4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk ke akun Skill Academy kamu!'])[1]/preceding::p[1]</value>
      <webElementGuid>dfa8d0d6-43b4-4ba4-9915-c8ae88c90275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email tidak valid'])[1]/preceding::p[2]</value>
      <webElementGuid>7c17ca31-b72a-42a7-9146-beb43214943d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>b2732613-5995-4dd5-9cbb-d406bb18986e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/p</value>
      <webElementGuid>33868d77-0d65-4daf-b868-3e48241bfc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>b9642dc8-1e50-4b9d-947a-0db80bd9d471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
