<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk ke akun Skill Academy kamu_css-1j6p4yb</name>
   <tag></tag>
   <elementGuidId>38f0729f-e9df-41b6-886f-447f9685a12b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-1j6p4yb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44d8bc70-215d-4ab0-bc60-caa1599cab26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>809e1aae-30ac-4cdf-9d01-5bf4fc358823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1j6p4yb</value>
      <webElementGuid>d160e3ff-ddf1-4aa9-b6df-7d68a3b43b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6119fe55-07cc-4e96-b820-4f09dfec9e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>5c1edd45-0172-4f47-803f-b75f14064076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[@class=&quot;css-fq9n1m&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1rmhad2&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/input[@class=&quot;css-1j6p4yb&quot;]</value>
      <webElementGuid>e43af681-ff33-4af4-b608-c2d49a21b75b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>6b64c688-9b89-4c0a-94ce-1abe13b22878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>0623e324-3e4a-4153-bdbe-dfa2807ca6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a12f9c9b-1d12-40b4-9d8e-c978661fb673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>199ef1fa-7725-4ef8-b78f-91e3915d697b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
