<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lanjut</name>
   <tag></tag>
   <elementGuidId>9693ab3d-d819-4dfc-8ead-03284ef3d112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>11adddd8-5b7e-4a99-88e7-e8abccd5bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>a60b6909-a148-4b4a-a06f-a137475cf296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>c7a37e1e-ae4f-45b8-aaab-df90b6a57987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[@class=&quot;css-sh4bij&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;css-1xgakyp&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1m5xake&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-2vw6wp&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>a704e421-6122-4c7f-b03c-467433000446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      <webElementGuid>c4b929c3-5663-4fa9-87d0-f9f1fe995489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus Exam'])[1]/following::p[9]</value>
      <webElementGuid>bd2979b8-b493-4dd8-97a4-89189687765c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai Seluruh Materi'])[1]/following::p[9]</value>
      <webElementGuid>14abeea1-3818-44dc-a538-8d493c1780c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjut']/parent::*</value>
      <webElementGuid>9b3ab000-7c2c-4531-a9f3-5ff65c65d6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/p</value>
      <webElementGuid>71fe8592-c102-409f-8e87-5a21973a7d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>d2dbb1eb-c393-4f03-9c2c-1665efbd764d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
