<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ulasan</name>
   <tag></tag>
   <elementGuidId>a1abe886-ea22-4bce-b362-873b0ac01555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='simple-tab-[object Object]']/span)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>86074e16-5525-4b65-804f-76a938792dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>a9d8d7ea-5957-4f4e-b6ec-d7a62bdf1250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ulasan</value>
      <webElementGuid>a9c7170c-2763-49a6-8a57-cfe620a79c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss91&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;MuiBox-root jss260 MenuBar__MenuBarWrap-sc-24ce6c-0 gIXumC&quot;]/div[@class=&quot;MuiTabs-root MenuBar__StyledTabs-sc-24ce6c-1 dPBFms&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-scrollable&quot;]/div[@class=&quot;MuiTabs-flexContainer&quot;]/button[@id=&quot;simple-tab-[object Object]&quot;]/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>b62e8e9c-b498-481b-8752-ac0e16315c0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='simple-tab-[object Object]']/span)[3]</value>
      <webElementGuid>348f5163-d167-4a55-bb8d-b83064909593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang'])[1]/following::span[2]</value>
      <webElementGuid>eb711c33-3529-43c7-bb51-f6a10750f131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekaman'])[1]/following::span[3]</value>
      <webElementGuid>880b2b85-d712-4f45-8846-f24d84b53d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskusi'])[1]/preceding::span[4]</value>
      <webElementGuid>61bb4143-b621-44aa-a2d9-c570a02d3141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ujian Praktek'])[1]/preceding::span[6]</value>
      <webElementGuid>3ba63c64-422e-411c-add6-2900f393f327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ulasan']/parent::*</value>
      <webElementGuid>8dfcd320-61b9-4b0c-a218-e43d3d27fe45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]/span</value>
      <webElementGuid>beb2e5fa-d37f-4b69-a605-bdef1391a050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ulasan' or . = 'Ulasan')]</value>
      <webElementGuid>9702769b-e398-4e43-950b-8f47078cd451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
