<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b</name>
   <tag></tag>
   <elementGuidId>2d057d3c-2f0c-4b63-bbee-1576e96383a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>723fa949-75a1-4a0f-8529-ebf967bdd3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectBoxBtn</value>
      <webElementGuid>6d604037-71cf-44f0-9f89-b1c8b6657c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>b4e883a0-994a-4c8e-b676-76bf3009d1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;jss852&quot;]/div[@class=&quot;questionSelectBox&quot;]/div[@class=&quot;selectBoxBtn&quot;]</value>
      <webElementGuid>ff064586-d5a2-48e4-b02d-0034f3dede80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div</value>
      <webElementGuid>1c142af2-93b2-4795-af1f-11277f38009e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you doing?'])[1]/following::div[2]</value>
      <webElementGuid>78f49b93-cd00-4f6c-b5c2-762661799411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::div[2]</value>
      <webElementGuid>d4388f66-6a82-4e47-a5cb-b563b71b5c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/preceding::div[1]</value>
      <webElementGuid>ff55f2ec-05a6-4589-9ace-9e7c7f23218d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='d'])[1]/preceding::div[3]</value>
      <webElementGuid>0cf4e9b2-5518-4ef4-a78c-41abc240d746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='b']/parent::*</value>
      <webElementGuid>95f8f939-22bc-40c9-b0f5-aae88d706843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>bd69aa30-86b7-454c-a751-893c82273605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'b' or . = 'b')]</value>
      <webElementGuid>62547f5d-44de-4d08-8484-5b48a048fcff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
