<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Berbahasa Apa dan Bagaimana</name>
   <tag></tag>
   <elementGuidId>8d884e58-d577-42e5-be1f-362aa65577fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div/div[2]/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.jss374</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>b4ff326a-48d1-49ea-943d-e170675d4768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss374</value>
      <webElementGuid>8c50920d-2697-4e3a-8ba6-b6e6ec03d709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berbahasa: Apa dan Bagaimana</value>
      <webElementGuid>7332fa3e-e466-416c-a398-dc663b20767b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss91&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;sideContent&quot;]/div[@class=&quot;jss370&quot;]/div[@class=&quot;MuiBox-root jss385 jss371&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root jss373 MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root jss375&quot;]/div[@class=&quot;MuiAccordionSummary-content&quot;]/h4[@class=&quot;jss374&quot;]</value>
      <webElementGuid>193f070f-110e-4ccf-abac-1106e29e3c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div/div[2]/div/div/div/h4</value>
      <webElementGuid>4de4a266-fa8f-4a97-b3b8-8b9d3382f80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersertifikat'])[1]/following::h4[1]</value>
      <webElementGuid>641c98e5-3ebb-4c2f-98ef-6ed7d4bc1d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cania Citta Irlanie'])[1]/following::h4[1]</value>
      <webElementGuid>9953e948-545d-48df-b8ce-f50c495d7aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Langkah Awal Belajar Bahasa Inggris'])[1]/preceding::h4[1]</value>
      <webElementGuid>e2b3788b-40ac-4325-87e3-75a3e03e9d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengenal Konsep Kata Benda dan Subjek'])[1]/preceding::h4[2]</value>
      <webElementGuid>11f2309f-0552-4311-92b2-8952ac94eb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Berbahasa: Apa dan Bagaimana']/parent::*</value>
      <webElementGuid>57b0ba8c-69dd-4e93-85bd-07d687d73506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>4adcced0-b309-489f-80f4-69978e61e29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Berbahasa: Apa dan Bagaimana' or . = 'Berbahasa: Apa dan Bagaimana')]</value>
      <webElementGuid>cf92ad97-96a7-4f8b-9935-303c97f34e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
