<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lanjut</name>
   <tag></tag>
   <elementGuidId>99c907e5-180e-482a-89e0-d4f697099c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>650fa83a-a15d-44bc-8315-4a15ead4481b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>2f1be96f-8aee-46e9-9be7-8d1cdc20cadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>88814b4e-9c83-42fa-ba00-e42e29bd91fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[@class=&quot;css-sh4bij&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;css-1xgakyp&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1m5xake&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-2vw6wp&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>89c53f3f-423b-48e4-96b3-f2e220682919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      <webElementGuid>baee6c5e-61d3-412c-8ad4-cde0a8a3b3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus Exam'])[1]/following::p[9]</value>
      <webElementGuid>72edd930-0f17-4e51-8f45-cc6d1fb9866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai Seluruh Materi'])[1]/following::p[9]</value>
      <webElementGuid>72104abc-03b8-4de7-985a-3a9374f1f0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjut']/parent::*</value>
      <webElementGuid>049424ac-27ad-4f38-9c23-60cefacbe392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/p</value>
      <webElementGuid>a48ed480-e2d4-47b9-9053-01346d02c986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>b6be746c-c907-47ec-a879-cdb3200014d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
