<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_MASUK</name>
   <tag></tag>
   <elementGuidId>f726f4f1-c6d8-49e6-8d95-66647ff1b9c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div[4]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>72b1fb44-08aa-454a-b106-1049884632c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>aad69181-ddda-4e48-a71e-72ca4ad2a0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASUK</value>
      <webElementGuid>38120c35-e3ae-4cbd-ae64-355c49ad5d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[@class=&quot;css-fq9n1m&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1rmhad2&quot;]/form[1]/div[@class=&quot;css-ggsuor&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1llbb9&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>92971544-06ed-49a4-934e-077266cddcb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div[4]/div/div/p</value>
      <webElementGuid>a2de979b-1dcb-4a48-b012-4f6578048a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password tidak valid'])[1]/following::p[2]</value>
      <webElementGuid>2b0a493e-870e-4347-ab64-a591957878ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email tidak valid'])[1]/following::p[3]</value>
      <webElementGuid>cbecd167-53d6-4643-a580-75a72c98d56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum memiliki akun? Silakan'])[1]/preceding::p[4]</value>
      <webElementGuid>42eb14ae-7054-4c59-b597-e79f761e2145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::p[4]</value>
      <webElementGuid>7118c351-a479-4505-b8ea-49932582120b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MASUK']/parent::*</value>
      <webElementGuid>1279483a-c5af-40a6-b952-13103c2d9d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/p</value>
      <webElementGuid>b086c776-63a3-43fa-ab68-8a44305ff53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'MASUK' or . = 'MASUK')]</value>
      <webElementGuid>fb0c6cef-1d28-415b-8a0d-54bcee893428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
