<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lihat Selengkapnya_css-1qx5mic</name>
   <tag></tag>
   <elementGuidId>6e506332-3d50-4fe5-b27e-bcf409de5a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1qx5mic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>265b4b5a-cd0e-414a-b131-95355a2af97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1qx5mic</value>
      <webElementGuid>4197b80d-46e2-4151-856e-cba6444effac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>certificate-image</value>
      <webElementGuid>452f40bd-d30b-4737-9069-724b778c0487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[@class=&quot;css-sh4bij&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[@class=&quot;css-d3eotr&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1qx5mic&quot;]</value>
      <webElementGuid>fa01a11b-db17-4ef1-9143-2b85d64527a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>c6cd16e2-108f-434c-b591-8f7c932753d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>ecb655f7-5d92-4639-b9b2-9553f44f1931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
