<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_MASUK</name>
   <tag></tag>
   <elementGuidId>8cba6d91-677e-4d34-97fc-88a51321f5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div[4]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c26dea70-5dbd-486b-81de-7c7f2d4be065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>c7a25db6-1e6a-4be1-b5ae-2ab057948af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASUK</value>
      <webElementGuid>0c9ad6ab-765d-4e2f-ae19-37312cee24eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[@class=&quot;css-fq9n1m&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1rmhad2&quot;]/form[1]/div[@class=&quot;css-ggsuor&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1llbb9&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>9a370805-3100-4b21-9459-147b5f63bf13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div[4]/div/div/p</value>
      <webElementGuid>b4db6cd9-4524-4d92-8f15-0deb03b806d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password tidak valid'])[1]/following::p[2]</value>
      <webElementGuid>c4ca263f-05ad-4a42-b372-b9c0a6b0f236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email tidak valid'])[1]/following::p[3]</value>
      <webElementGuid>b8825ce9-f13d-46b1-bb1e-ec4383f69793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum memiliki akun? Silakan'])[1]/preceding::p[4]</value>
      <webElementGuid>6a321487-0d4d-4809-ab89-6fe51c11d7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::p[4]</value>
      <webElementGuid>885f55bc-b716-47fe-89b6-b3f2b02d3af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MASUK']/parent::*</value>
      <webElementGuid>15345d3f-50e5-48e4-8c39-0f9cad8e797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/p</value>
      <webElementGuid>f5a4b9eb-d087-4385-b591-7fa4618a4f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'MASUK' or . = 'MASUK')]</value>
      <webElementGuid>8a98679a-de2c-45e9-a08c-e1e42ad73b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
