<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk ke akun Skill Academy kamu_css-1j6p4yb</name>
   <tag></tag>
   <elementGuidId>d3f86181-a652-4d9c-a235-02f0fed41683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-1j6p4yb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b60f98bd-5dfc-4bba-9839-fb860d412ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed866194-6179-42e8-9304-206892e34bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1j6p4yb</value>
      <webElementGuid>b9c21ffe-9d1d-4a02-b0ac-c692e2e6793d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>01784be4-1124-4fee-8aca-f38d6949bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>c6c9099a-9aeb-4c78-9965-762f89ba9e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;css-7p994x&quot;]/div[@class=&quot;css-1f9vorr&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[@class=&quot;css-fq9n1m&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1rmhad2&quot;]/form[1]/div[@class=&quot;css-1fxjj6r&quot;]/input[@class=&quot;css-1j6p4yb&quot;]</value>
      <webElementGuid>1360f557-64a8-4809-831f-5407952cc22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>7f46d039-a7c8-4181-9577-4ce9f6f5c5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>32219bd9-e89f-482f-b3fc-fbd489580bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>97db9dc1-69fb-4608-9dbd-51eb21a89f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>98893974-3500-47f3-be8f-7dbffb2e195f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
