<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b5731bd2-4c33-4fbc-9a84-5ce9ee4d05fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Gopay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div/div[2]/div/div/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6b605c12-e73e-4dfc-946d-832e992d9032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>94e645fd-a889-449f-adb2-566b9905c880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zenius.net/product/zenpro/paymentIcons/gopay.png</value>
      <webElementGuid>5f193342-a012-45d5-8ff6-f0a5c0ec46fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gopay</value>
      <webElementGuid>f3e4c886-d8ba-43ba-bf92-cb28da6ccf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss390&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-10&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-12 MuiGrid-grid-md-12 MuiGrid-grid-lg-8 MuiGrid-grid-xl-8&quot;]/div[2]/div[@class=&quot;MuiFormGroup-root&quot;]/div[@class=&quot;jss397 bg-gray-100 border-solid border border-gray-200 rounded-md pt-3 pl-3&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text border-solid border border-gray-200 rounded-md mb-3 mr-3&quot;]/span[@class=&quot;MuiButton-label&quot;]/img[1]</value>
      <webElementGuid>c24dd0da-207e-4ca0-b79b-ae72826af8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div/div[2]/div/div/button/span/img</value>
      <webElementGuid>06ac0345-6fed-4ba1-9e63-d2951f2011ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gopay']</value>
      <webElementGuid>c5fc6400-0f4b-48ba-a776-62531df79fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/img</value>
      <webElementGuid>323a9da3-e3f2-4113-925e-b88e13fb973d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://zenius.net/product/zenpro/paymentIcons/gopay.png' and @alt = 'Gopay']</value>
      <webElementGuid>740437d1-167a-4e12-9aa2-622b352ac774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
