<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fb21f081-e4d2-4507-aa17-a3e920b79326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[9]/div[5]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5c9de99e-e112-49ba-a8e7-1bd089c388b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Play Bold</value>
      <webElementGuid>2a4d442a-14fc-46d8-9647-6546a3b11be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icon/Play_Bold.svg</value>
      <webElementGuid>9bb31532-32e9-4714-b3a6-de8170c53be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>8e204dbd-08e5-4a05-af6c-3ec2501cba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>995405f6-156e-4dac-801c-c2b40c445856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[1]/div[@class=&quot;css-14006f7&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-xz0cmf&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1lsg1z4&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1uudw9a&quot;]/img[1]</value>
      <webElementGuid>86408211-e721-430b-a532-03a7f66a6bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[9]/div[5]/div/div[2]/div/div/img</value>
      <webElementGuid>6517e587-1df5-4dce-ad9f-51fd077ac644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Play Bold'])[58]</value>
      <webElementGuid>c7c7acb2-f901-4492-9e46-a49165438a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[5]/div/div[2]/div/div/img</value>
      <webElementGuid>a9402bd9-1e0e-4c8f-99a2-5d92c0eb215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Play Bold' and @src = '/assets/icon/Play_Bold.svg']</value>
      <webElementGuid>dc5537f7-d98c-4646-ab4d-e3f1e21dd527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
