<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>56de6607-635d-41c2-a845-98489baf5f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;File Bold&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[10]/div[2]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>98d26c4b-318a-493d-a0c2-7b6960d194f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>File Bold</value>
      <webElementGuid>e6c8937a-40ae-403c-b1c6-dd02ca4b4f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icon/File_Bold.svg</value>
      <webElementGuid>c7873c85-1944-49ed-9279-d11c7fc2f3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>974e4bb2-c66b-4d99-b8b1-90c53e06b737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>97c4720e-bcc9-436a-9bac-65a107166a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[1]/div[@class=&quot;css-14006f7&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-xz0cmf&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1lsg1z4&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1uudw9a&quot;]/img[1]</value>
      <webElementGuid>9a0c9269-ba73-48ba-974c-d7c7929e978b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[10]/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>bd15a2f7-d058-40de-81b9-bfafcebf9c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='File Bold']</value>
      <webElementGuid>b128e4d5-6922-44fc-81b1-1105bc94dbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>2906f570-d43a-4ed6-b75d-8f4d68cbccc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'File Bold' and @src = '/assets/icon/File_Bold.svg']</value>
      <webElementGuid>ba385117-2b69-41a8-94d0-43bd80550f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
