<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_LIHAT DOKUMEN</name>
   <tag></tag>
   <elementGuidId>1b770b99-98ff-41bf-979a-f5c164f91a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/a/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>630298c7-cc20-4a40-b254-c74408965b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>b81ac13e-a275-41c4-8919-cc91b9759987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LIHAT DOKUMEN</value>
      <webElementGuid>14802dfd-a099-40f8-8c99-16d32b1366a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[2]/div[@class=&quot;css-1a66z0j&quot;]/div[@class=&quot;css-nukipx&quot;]/div[@class=&quot;css-j1493g&quot;]/a[@class=&quot;css-rwj60y&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1y23cti&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>7b8535cd-cd55-49ac-8fa9-8423865c19ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/a/div/div/p</value>
      <webElementGuid>10bad298-da27-494e-9e46-9e861a412dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menggunakan Data Science untuk Mengembangkan Bisnis bagi Data Scientist'])[1]/following::p[153]</value>
      <webElementGuid>fe844047-b754-4089-9fc2-fdb284382020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LIHAT DOKUMEN']/parent::*</value>
      <webElementGuid>ef492426-3069-4648-9379-003ce9a8e69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/p</value>
      <webElementGuid>96b2fac9-3a67-4bbf-a7a5-97f4780d4485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'LIHAT DOKUMEN' or . = 'LIHAT DOKUMEN')]</value>
      <webElementGuid>615f9dd5-e8df-4a44-b5c0-abd3ccc212d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
