<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>dd039acc-f4d5-4171-95df-5d602b6c7d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>18264763-9691-4826-9438-0d6fa7e60b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-z88rz8</value>
      <webElementGuid>ce58c06b-cd27-4ceb-bb65-da1777e1146e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>e78b7440-71c5-466a-b10c-cb2e5056f32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1s5sjt4&quot;]/div[2]/div[2]/div[@class=&quot;css-1a66z0j&quot;]/div[@class=&quot;css-nukipx&quot;]/div[@class=&quot;css-17tc0h1&quot;]/div[@class=&quot;css-s3u3bt&quot;]/div[@class=&quot;css-avf9nl&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-gclzmy&quot;]/div[@class=&quot;css-cennm4&quot;]/p[@class=&quot;css-z88rz8&quot;]</value>
      <webElementGuid>3d1c94e3-f18f-44f7-9607-1613c5394bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/p</value>
      <webElementGuid>13d0bd11-0a6a-4302-8f74-e329df9989cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playback speed'])[2]/following::p[3]</value>
      <webElementGuid>5b1a1a7b-b876-40a6-bba4-aa4af4db01e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_back'])[4]/following::p[3]</value>
      <webElementGuid>5468b12f-799b-4502-8bdf-25883cfd9ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>fac7b859-2192-4674-bd57-7bfd6e27e4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/p</value>
      <webElementGuid>24e0114e-2e3a-48eb-8794-2e91e17bae69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>64427e9d-a97f-4bc7-8dfe-4e0212073a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
