<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a2a6da15-a457-4cfe-90e5-d88dfa56ff4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Perempuan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[6]/div/button[2]/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bdca4273-f59d-4870-9b64-6f5e0f6f34ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zenius.net/product/zenpro/images/female.png</value>
      <webElementGuid>1d8db074-88b0-4c7c-aeb2-03f6259a6937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Perempuan</value>
      <webElementGuid>eaf2c5e8-ef17-4440-b871-86ad88bb9c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss369&quot;]/div[@class=&quot;jss425&quot;]/div[@class=&quot;content null&quot;]/div[@class=&quot;gender&quot;]/div[@class=&quot;MuiToggleButtonGroup-root&quot;]/button[@class=&quot;MuiButtonBase-root MuiToggleButton-root MuiToggleButtonGroup-grouped MuiToggleButtonGroup-groupedHorizontal&quot;]/span[@class=&quot;MuiToggleButton-label&quot;]/img[1]</value>
      <webElementGuid>838bf3df-a921-4707-b81c-c06fd4c76cf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[6]/div/button[2]/span/img</value>
      <webElementGuid>f15f82bf-a314-485f-ac6c-d0482c357aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Perempuan']</value>
      <webElementGuid>50979a97-e407-4602-8483-81f7f4f3697e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/img</value>
      <webElementGuid>3524845c-6fc9-4434-8807-160a939b885a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://zenius.net/product/zenpro/images/female.png' and @alt = 'Perempuan']</value>
      <webElementGuid>c7e57125-fbd3-46bb-8221-59bbd69efae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
