<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Meningkatkan performa kerja</name>
   <tag></tag>
   <elementGuidId>abbff581-ec31-4022-982f-44d82297b29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>53f78b56-b581-4779-b1ae-7d03d94a3801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label</value>
      <webElementGuid>d310ff4e-6399-4be0-943e-542c1c9211e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meningkatkan performa kerja</value>
      <webElementGuid>1a27f1e2-aa8b-4fd5-bd70-7ffaf2cc0047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss369&quot;]/div[@class=&quot;jss401&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;goalDiv&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text customButton&quot;]/span[@class=&quot;MuiButton-label&quot;]</value>
      <webElementGuid>8bfbf008-7c5b-43c5-9ea1-86fdedc2a090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/button[2]/span</value>
      <webElementGuid>b7304a64-232f-48d0-9eae-440f43eb1c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapat pekerjaan'])[1]/following::span[2]</value>
      <webElementGuid>65b811d6-0afb-467b-a0ac-bae898e3875f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa tujuan utamamu?'])[1]/following::span[3]</value>
      <webElementGuid>ad988a7a-39c0-467c-baeb-6d9741539b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pindah pekerjaan'])[1]/preceding::span[4]</value>
      <webElementGuid>ec2dd8b0-4a8a-4d0e-83dd-71e3e96b8853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merintis/mengembangkan bisnis'])[1]/preceding::span[6]</value>
      <webElementGuid>c2f1bbf3-6d29-44fe-9931-c98593ecf263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Meningkatkan performa kerja']/parent::*</value>
      <webElementGuid>87542142-0e9f-4ccd-b18c-4028f91184b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>5bc43174-6b9a-445f-a2f2-d2934ba166f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Meningkatkan performa kerja' or . = 'Meningkatkan performa kerja')]</value>
      <webElementGuid>c840c049-e4bd-4069-b5a4-cfb4817947ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
