<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lanjut</name>
   <tag></tag>
   <elementGuidId>cba7449c-675a-4034-a687-f97e5fc1469b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-wc5b3e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>113a93fb-9725-4d12-b966-ec50678c0ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wc5b3e</value>
      <webElementGuid>eeb44ff7-1bd0-43c1-8920-c30b38ed28e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>ddc37083-4212-40d8-b61a-26cf68ce7ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-scrollview-children-container&quot;)/div[@class=&quot;css-sh4bij&quot;]/div[@class=&quot;css-13ookwh&quot;]/div[@class=&quot;css-ipztt8&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;css-1xgakyp&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-1m5xake&quot;]/div[@class=&quot;css-cennm4&quot;]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-2vw6wp&quot;]/p[@class=&quot;css-wc5b3e&quot;]</value>
      <webElementGuid>8fb57f32-06a8-4103-b6cb-56c8fd8cc039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-scrollview-children-container']/div[3]/div/div[2]/div/div/div[2]/div[3]/div/div[3]/div[3]/div[3]/div/p</value>
      <webElementGuid>5fa6f7b7-419b-414b-b0dc-167294aa8fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lulus Exam'])[1]/following::p[9]</value>
      <webElementGuid>dd5f3734-ed91-44ba-8a2d-a2b68b38a962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai Seluruh Materi'])[1]/following::p[9]</value>
      <webElementGuid>87c4df48-5e8c-4448-acda-5c46838ecfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjut']/parent::*</value>
      <webElementGuid>8c61ba48-b63a-4532-9ed5-04a6531786d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/p</value>
      <webElementGuid>81384e67-b5f2-4dc0-8ecf-31f99958506a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>40808ed0-738a-4c3e-9980-a2fa960c005e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
