<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kategori_css-9pa8cd</name>
   <tag></tag>
   <elementGuidId>40a5c760-169f-4ae1-b90e-9248a50e68b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-175oi2r.r-1loqt21.r-1otgn73 > div.css-175oi2r.r-1mlwlqe.r-1udh08x.r-417010.is_Image._w-24px._h-24px._zi-1._pos-relative > img.css-9pa8cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/span/div/span/div/div/div/div/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5af37138-4176-4b8d-aadd-1164c9b0b677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed2164c0-82e0-467c-869e-b15b381bc21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn2.skillacademy.com/skillacademy-web/public/assets/icons/SearchBlack.svg</value>
      <webElementGuid>d4c75217-1da8-4de1-9cc7-a8f6e0c2b88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-9pa8cd</value>
      <webElementGuid>c7a29e8e-cbf4-4514-b64d-c06c6e612454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/span[@class=&quot;t_sub_theme t_light _dsp_contents&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/span[@class=&quot;t_sub_theme t_dark _dsp_contents&quot;]/div[@class=&quot;is_YStack  _bg-rsi03t _ox-hidden _oy-hidden _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_YStack  _dsp-_gtMd_flex _dsp-none _bg-57q3d6 _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_YStack  _w-_gtLg_12c3duh _w-_gtMd_11v1rga _w-_gtSm_11e0523 _pr-1aj148u _pl-1aj148u _w-10011 _mt-auto _mr-auto _mb-auto _ml-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _ai-center _jc-7aqssh _pr-1aj149p _pl-1aj149p _pt-1aj149p _pb-1aj149p _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_XStack  _dsp-_gtXs_flex _ai-center _fg-1 _fs-1 _fb-auto _dsp-none _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_XStack  _pos-relative _fd-row _miw-0px _mih-0px _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _zi-4 _r-1aj148u _ai-center _b-0px _t-0px _pos-absolute _fd-row _miw-0px _mih-0px _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;css-175oi2r r-1loqt21 r-1otgn73&quot;]/div[@class=&quot;css-175oi2r r-1mlwlqe r-1udh08x r-417010 is_Image _w-24px _h-24px _zi-1 _pos-relative&quot;]/img[@class=&quot;css-9pa8cd&quot;]</value>
      <webElementGuid>50864b3e-3232-4907-90cb-bce4dff59e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/span/div/span/div/div/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>6ff59a40-779b-45ae-b069-cab967331f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn2.skillacademy.com/skillacademy-web/public/assets/icons/SearchBlack.svg')]</value>
      <webElementGuid>0d124545-f838-422b-a034-8f06a5948a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>8722ffb6-eeae-492c-b96c-e96d0cf1a6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn2.skillacademy.com/skillacademy-web/public/assets/icons/SearchBlack.svg']</value>
      <webElementGuid>ea1db52f-178a-4515-9049-f976d9b0d4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
