<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_css-11aywtz r-6taxm2 is_Inpu_8332b3</name>
   <tag></tag>
   <elementGuidId>46d77d48-a9dd-4eee-9958-b0ed035dbe9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-11aywtz.r-6taxm2.is_Input.font_body._btc-0hover-1byp41v._brc-0hover-1byp41v._bbc-0hover-1byp41v._blc-0hover-1byp41v._btc-0focus-1b0a2ef._brc-0focus-1b0a2ef._bbc-0focus-1b0a2ef._blc-0focus-1b0a2ef._btw-0focus-2px._brw-0focus-2px._bbw-0focus-2px._blw-0focus-2px._mr-0focus--1px._ml-0focus--1px._bbs-0focus-solid._bts-0focus-solid._bls-0focus-solid._brs-0focus-solid._pr-lrpiu9._fg-1._fs-1._fb-auto._btlr-lmimb3._btrr-lmimb3._bbrr-lmimb3._bblr-lmimb3._pt-1aj149p._pb-1aj149p._pl-1aj149p._btc-1ckdigv._brc-1ckdigv._bbc-1ckdigv._blc-1ckdigv._bg-1ckdj6p._col-d0tu4wolg._ff-4xduee._h-qnlo9k._btw-1px._brw-1px._bbw-1px._blw-1px._outlineWidth-0px._miw-0px._bbs-solid._bts-solid._bls-solid._brs-solid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='cpns']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>955df2db-9e76-42cd-a3b8-17ccf0ecbaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kamu ingin menguasai skill apa hari ini?</value>
      <webElementGuid>f148b089-24a6-4482-864d-8b7ac6755d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>0d060c5a-dafb-4695-b0f6-a5c755789d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7d179c93-f3a5-4b0b-8b9a-a023964b4277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>41701ef7-16d8-4211-bb5b-9a3fd1c01ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>145fad47-1602-4f13-8a27-5527ae1d37cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6252715-d025-4248-869d-b44fdc53dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a5f2026-09d1-4657-9eca-bac1569f9278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-6taxm2 is_Input font_body _btc-0hover-1byp41v _brc-0hover-1byp41v _bbc-0hover-1byp41v _blc-0hover-1byp41v _btc-0focus-1b0a2ef _brc-0focus-1b0a2ef _bbc-0focus-1b0a2ef _blc-0focus-1b0a2ef _btw-0focus-2px _brw-0focus-2px _bbw-0focus-2px _blw-0focus-2px _mr-0focus--1px _ml-0focus--1px _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _pr-lrpiu9 _fg-1 _fs-1 _fb-auto _btlr-lmimb3 _btrr-lmimb3 _bbrr-lmimb3 _bblr-lmimb3 _pt-1aj149p _pb-1aj149p _pl-1aj149p _btc-1ckdigv _brc-1ckdigv _bbc-1ckdigv _blc-1ckdigv _bg-1ckdj6p _col-d0tu4wolg _ff-4xduee _h-qnlo9k _btw-1px _brw-1px _bbw-1px _blw-1px _outlineWidth-0px _miw-0px _bbs-solid _bts-solid _bls-solid _brs-solid</value>
      <webElementGuid>3bc98920-3837-4b4a-8355-e1a50475e565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cpns</value>
      <webElementGuid>58f51e6e-725b-4dae-ac57-c3a0ecd3d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/span[@class=&quot;t_sub_theme t_light _dsp_contents&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/span[@class=&quot;t_sub_theme t_dark _dsp_contents&quot;]/div[@class=&quot;is_YStack  _bg-rsi03t _ox-hidden _oy-hidden _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_YStack  _dsp-_gtMd_flex _dsp-none _bg-57q3d6 _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_YStack  _w-_gtLg_12c3duh _w-_gtMd_11v1rga _w-_gtSm_11e0523 _pr-1aj148u _pl-1aj148u _w-10011 _mt-auto _mr-auto _mb-auto _ml-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/div[@class=&quot;is_XStack  _ai-center _jc-7aqssh _pr-1aj149p _pl-1aj149p _pt-1aj149p _pb-1aj149p _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box _fb-auto _dsp-flex _fs-0&quot;]/div[@class=&quot;is_XStack  _dsp-_gtXs_flex _ai-center _fg-1 _fs-1 _fb-auto _dsp-none _fd-row _miw-0px _mih-0px _pos-relative _bxs-border-box&quot;]/div[@class=&quot;is_YStack  _fg-1 _fs-1 _fb-auto _fd-column _miw-0px _mih-0px _pos-relative _bxs-border-box _dsp-flex _ai-stretch&quot;]/div[@class=&quot;is_XStack  _pos-relative _fd-row _miw-0px _mih-0px _bxs-border-box _fb-auto _dsp-flex _fs-0 _ai-stretch&quot;]/input[@class=&quot;css-11aywtz r-6taxm2 is_Input font_body _btc-0hover-1byp41v _brc-0hover-1byp41v _bbc-0hover-1byp41v _blc-0hover-1byp41v _btc-0focus-1b0a2ef _brc-0focus-1b0a2ef _bbc-0focus-1b0a2ef _blc-0focus-1b0a2ef _btw-0focus-2px _brw-0focus-2px _bbw-0focus-2px _blw-0focus-2px _mr-0focus--1px _ml-0focus--1px _bbs-0focus-solid _bts-0focus-solid _bls-0focus-solid _brs-0focus-solid _pr-lrpiu9 _fg-1 _fs-1 _fb-auto _btlr-lmimb3 _btrr-lmimb3 _bbrr-lmimb3 _bblr-lmimb3 _pt-1aj149p _pb-1aj149p _pl-1aj149p _btc-1ckdigv _brc-1ckdigv _bbc-1ckdigv _blc-1ckdigv _bg-1ckdj6p _col-d0tu4wolg _ff-4xduee _h-qnlo9k _btw-1px _brw-1px _bbw-1px _blw-1px _outlineWidth-0px _miw-0px _bbs-solid _bts-solid _bls-solid _brs-solid&quot;]</value>
      <webElementGuid>975f172a-3590-4578-a3a9-c1900893e236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='cpns']</value>
      <webElementGuid>08709499-adaa-4d9a-9588-944eb315892c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/span/div/span/div/div/div/div/div/div/div/input</value>
      <webElementGuid>dd44328d-574d-419a-b3ec-f3a471eb1cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4897cd71-1005-4eb7-aaf2-fa6eabed3114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kamu ingin menguasai skill apa hari ini?' and @type = 'text']</value>
      <webElementGuid>36c2ef26-a295-4ee0-94e7-7046e5ed6093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
